### PR TITLE
Handle an improved comment

### PR DESCRIPTION
**Pull request by guyzmo**
Hello 👋

Thank you for your little github action! 🙇

I made a fork and updated the comment to make it more visible in the comments ~and also add a link to the last build.~

And added parameters with the different URL returned by the chromatic GA, so it can be called as follows:

```yaml
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true

      - name: Publish Storybook Link in the comments
        uses: dannyhw/storybook-chromatic-link-comment@v0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-url: ${{ steps.chromatic.outputs.url }}
          build-url: ${{ steps.chromatic.outputs.buildUrl }}
          storybook-url: ${{ steps.chromatic.outputs.storybookUrl }}
```

to show the following message:

> ## 🔍 Visual review for your branch is published 🔍
> 
> Here are the links to:
> 
> - the [Visual Review Page](https://www.chromatic.com/review?appId=AAAAA&number=0&type=linked)
> - the [latest build on chromatic](https://www.chromatic.com/build?appId=AAAAA&number=42)
> - the [full storybook](https://myfeature-AAAAA.chromatic.com)

### CODE REVIEW

**Comment by guyzmo** [comment]
thinking about it, it could be improved by using [the urls returned from the chromatic's GA](https://www.chromatic.com/docs/github-actions/#outputs): `url` / `buildUrl` / `storybookUrl`, that could be configured as:

```
      - name: Publish Storybook Link in the comments
        uses: dannyhw/storybook-chromatic-link-comment@v0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-url: ${{ steps.chromatic.outputs.url }}
          build-url: ${{ steps.chromatic.outputs.buildUrl }}
          storybook-url: ${{ steps.chromatic.outputs.storybookUrl }}
```

(app-id would then not be needed).

**Comment by guyzmo** [comment]
I just did update the PR for that 😎

**Comment by guyzmo** [comment]
N.B.: this PR is synced with my main branch (that's not very neat but I tried doing a fork without a checkout locally…) and I just changed the actions.yml. So if you're thinking on merging my changes, you should revert [9466dc9](https://github.com/dannyhw/storybook-chromatic-link-comment/pull/103/commits/9466dc95e1d8ccfb9d0c3643ba28bc9e7a1d08d6) 😉

**Comment by dannyhw** [comment]
Hey im glad this was useful for you and thanks for sharing your improvements. 

By the way if the pr is made from a branch on the fork then you dont need to worry about main getting synced up with the pr.

**Comment by guyzmo** [comment]
the issue was trying to use github itself for making a PR (using a only phone 🫣), I'll check it out tomorrow and make a proper PR from another branch ☺

**Comment by guyzmo** [comment]
discarding this PR in favor of #104 (we cannot change a source branch of a PR, so I'm closing this one)

**Pull request closed without merging**
